export enum Errors {
  ERR_DATABASE = "ERR_DATABASE",
  ERR_CONNECTION_REFUSED = "ERR_CONNECTION_REFUSED",
  ERR_QUERY_EXECUTION = "ERR_QUERY_EXECUTION",
  ERR_MISSING_POOL = "ERR_MISSING_POOL",

  ERR_UTILITY = "ERR_UTILITY",

  ERR_RESPONSE = "ERR_RESPONSE",
  ERR_BAD_REQUEST = "ERR_BAD_REQUEST",
  ERR_UNAUTHORIZED = "ERR_UNAUTHORIZED",
  ERR_FORBIDDEN = "ERR_FORBIDDEN",
  ERR_NOT_FOUND = "ERR_NOT_FOUND",
  ERR_UNSUPPORTED_MEDIA_TYPE = "ERR_UNSUPPORTED_MEDIA_TYPE",
  ERR_INTERNAL_SERVER = "ERR_INTERNAL_SERVER",
  ERR_CONFLICT = "ERR_CONFLICT",

  ERR_VALIDATION = "ERR_VALIDATION",
  ERR_MISSING_FIELD = "ERR_MISSING_FIELD",
  ERR_REQUIRED_FIELD = "ERR_REQUIRED_FIELD",
}
